package com.avalon.ms.dao.mybatis.mapper;

import com.avalon.ms.dao.entity.BhifPayIbankParaInfo;
import java.util.List;

public interface BhifPayIbankParaInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhif_pay_ibank_para_info
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    int insert(BhifPayIbankParaInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhif_pay_ibank_para_info
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    List<BhifPayIbankParaInfo> selectAll();
    
    void update(BhifPayIbankParaInfo record);
    
    void batchUpdate(List<BhifPayIbankParaInfo> list);
}