package com.avalon.ms.dao.mybatis.mapper;

import com.avalon.ms.dao.entity.KyBranchbankinfos;
import java.util.List;

public interface KyBranchbankinfosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY_BRANCHBANKINFOS
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY_BRANCHBANKINFOS
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    int insert(KyBranchbankinfos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY_BRANCHBANKINFOS
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    KyBranchbankinfos selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY_BRANCHBANKINFOS
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    List<KyBranchbankinfos> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY_BRANCHBANKINFOS
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    int updateByPrimaryKey(KyBranchbankinfos record);
}