package com.avalon.ms.dao.mybatis.mapper;

import com.avalon.ms.dao.entity.KySubaccount;
import java.util.List;

public interface KySubaccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY_SUBACCOUNT
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    int deleteByPrimaryKey(String custcertno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY_SUBACCOUNT
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    int insert(KySubaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY_SUBACCOUNT
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    KySubaccount selectByPrimaryKey(String custcertno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY_SUBACCOUNT
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    List<KySubaccount> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY_SUBACCOUNT
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    int updateByPrimaryKey(KySubaccount record);
}