package com.avalon.ms.dao.mybatis.mapper;

import com.avalon.ms.dao.entity.MsOperatorRole;
import java.util.List;

public interface MsOperatorRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_operator_role
     *
     * @mbg.generated Tue Aug 29 13:53:06 CST 2017
     */
    int insert(MsOperatorRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_operator_role
     *
     * @mbg.generated Tue Aug 29 13:53:06 CST 2017
     */
    List<MsOperatorRole> selectAll();
}