package com.avalon.ms.dao.mybatis.mapper;

import com.avalon.ms.dao.entity.TFile;
import java.util.List;

public interface TFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbg.generated Mon Oct 30 17:51:47 CST 2017
     */
    int insert(TFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbg.generated Mon Oct 30 17:51:47 CST 2017
     */
    List<TFile> selectAll();
}