package com.avalon.ms.dao.entity;

import java.util.Date;

public class BhifPayIbankParaInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.DATA_DT
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private Date dataDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.BANK_NUM
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private String bankNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.PAY_IBANK_NUM
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private String payIbankNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.IBANK_CATE_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private String ibankCateCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.LINE_TYP_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private String lineTypCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.BELG_DRCT_PRTC_LINE_IBANK_NUM
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private String belgDrctPrtcLineIbankNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.BELG_LPR_IBANK_NUM
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private String belgLprIbankNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.CITIC_UP_PRTC_ORG_IBANK_STR
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private String citicUpPrtcOrgIbankStr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.UNTK_LINE_IBANK_NUM
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private String untkLineIbankNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.BELG_PBC_IBANK_NUM
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private String belgPbcIbankNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.BELG_NODE_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private String belgNodeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.BELG_URBN_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private String belgUrbnCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.PAY_IBANK_FULL_NM
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private String payIbankFullNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.PAY_IBANK_SHT_NM
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private String payIbankShtNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.JOIN_BIZ_SYS_ID_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private String joinBizSysIdCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.JOIN_LARG_AMT_SYS_STAT_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private String joinLargAmtSysStatCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.JOIN_SML_AMT_SYS_STAT_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private String joinSmlAmtSysStatCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.JOIN_WBANK_SYS_STAT_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private String joinWbankSysStatCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.ADDR
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.ZIP_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private String zipCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.CONT_TEL
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private String contTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.EML_ADDR
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private String emlAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.SPRT_ONE_TWO_AGENT_TYP_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private String sprtOneTwoAgentTypCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.VALID_IND
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private String validInd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.SETUP_TMSTP
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private Date setupTmstp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.UPD_TMSTP
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private Date updTmstp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.EFFT_DT
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private Date efftDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhif_pay_ibank_para_info.INVLDTN_DT
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    private Date invldtnDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.DATA_DT
     *
     * @return the value of bhif_pay_ibank_para_info.DATA_DT
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public Date getDataDt() {
        return dataDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.DATA_DT
     *
     * @param dataDt the value for bhif_pay_ibank_para_info.DATA_DT
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setDataDt(Date dataDt) {
        this.dataDt = dataDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.BANK_NUM
     *
     * @return the value of bhif_pay_ibank_para_info.BANK_NUM
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public String getBankNum() {
        return bankNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.BANK_NUM
     *
     * @param bankNum the value for bhif_pay_ibank_para_info.BANK_NUM
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setBankNum(String bankNum) {
        this.bankNum = bankNum == null ? null : bankNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.PAY_IBANK_NUM
     *
     * @return the value of bhif_pay_ibank_para_info.PAY_IBANK_NUM
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public String getPayIbankNum() {
        return payIbankNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.PAY_IBANK_NUM
     *
     * @param payIbankNum the value for bhif_pay_ibank_para_info.PAY_IBANK_NUM
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setPayIbankNum(String payIbankNum) {
        this.payIbankNum = payIbankNum == null ? null : payIbankNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.IBANK_CATE_CD
     *
     * @return the value of bhif_pay_ibank_para_info.IBANK_CATE_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public String getIbankCateCd() {
        return ibankCateCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.IBANK_CATE_CD
     *
     * @param ibankCateCd the value for bhif_pay_ibank_para_info.IBANK_CATE_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setIbankCateCd(String ibankCateCd) {
        this.ibankCateCd = ibankCateCd == null ? null : ibankCateCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.LINE_TYP_CD
     *
     * @return the value of bhif_pay_ibank_para_info.LINE_TYP_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public String getLineTypCd() {
        return lineTypCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.LINE_TYP_CD
     *
     * @param lineTypCd the value for bhif_pay_ibank_para_info.LINE_TYP_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setLineTypCd(String lineTypCd) {
        this.lineTypCd = lineTypCd == null ? null : lineTypCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.BELG_DRCT_PRTC_LINE_IBANK_NUM
     *
     * @return the value of bhif_pay_ibank_para_info.BELG_DRCT_PRTC_LINE_IBANK_NUM
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public String getBelgDrctPrtcLineIbankNum() {
        return belgDrctPrtcLineIbankNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.BELG_DRCT_PRTC_LINE_IBANK_NUM
     *
     * @param belgDrctPrtcLineIbankNum the value for bhif_pay_ibank_para_info.BELG_DRCT_PRTC_LINE_IBANK_NUM
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setBelgDrctPrtcLineIbankNum(String belgDrctPrtcLineIbankNum) {
        this.belgDrctPrtcLineIbankNum = belgDrctPrtcLineIbankNum == null ? null : belgDrctPrtcLineIbankNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.BELG_LPR_IBANK_NUM
     *
     * @return the value of bhif_pay_ibank_para_info.BELG_LPR_IBANK_NUM
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public String getBelgLprIbankNum() {
        return belgLprIbankNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.BELG_LPR_IBANK_NUM
     *
     * @param belgLprIbankNum the value for bhif_pay_ibank_para_info.BELG_LPR_IBANK_NUM
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setBelgLprIbankNum(String belgLprIbankNum) {
        this.belgLprIbankNum = belgLprIbankNum == null ? null : belgLprIbankNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.CITIC_UP_PRTC_ORG_IBANK_STR
     *
     * @return the value of bhif_pay_ibank_para_info.CITIC_UP_PRTC_ORG_IBANK_STR
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public String getCiticUpPrtcOrgIbankStr() {
        return citicUpPrtcOrgIbankStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.CITIC_UP_PRTC_ORG_IBANK_STR
     *
     * @param citicUpPrtcOrgIbankStr the value for bhif_pay_ibank_para_info.CITIC_UP_PRTC_ORG_IBANK_STR
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setCiticUpPrtcOrgIbankStr(String citicUpPrtcOrgIbankStr) {
        this.citicUpPrtcOrgIbankStr = citicUpPrtcOrgIbankStr == null ? null : citicUpPrtcOrgIbankStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.UNTK_LINE_IBANK_NUM
     *
     * @return the value of bhif_pay_ibank_para_info.UNTK_LINE_IBANK_NUM
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public String getUntkLineIbankNum() {
        return untkLineIbankNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.UNTK_LINE_IBANK_NUM
     *
     * @param untkLineIbankNum the value for bhif_pay_ibank_para_info.UNTK_LINE_IBANK_NUM
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setUntkLineIbankNum(String untkLineIbankNum) {
        this.untkLineIbankNum = untkLineIbankNum == null ? null : untkLineIbankNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.BELG_PBC_IBANK_NUM
     *
     * @return the value of bhif_pay_ibank_para_info.BELG_PBC_IBANK_NUM
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public String getBelgPbcIbankNum() {
        return belgPbcIbankNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.BELG_PBC_IBANK_NUM
     *
     * @param belgPbcIbankNum the value for bhif_pay_ibank_para_info.BELG_PBC_IBANK_NUM
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setBelgPbcIbankNum(String belgPbcIbankNum) {
        this.belgPbcIbankNum = belgPbcIbankNum == null ? null : belgPbcIbankNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.BELG_NODE_CD
     *
     * @return the value of bhif_pay_ibank_para_info.BELG_NODE_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public String getBelgNodeCd() {
        return belgNodeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.BELG_NODE_CD
     *
     * @param belgNodeCd the value for bhif_pay_ibank_para_info.BELG_NODE_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setBelgNodeCd(String belgNodeCd) {
        this.belgNodeCd = belgNodeCd == null ? null : belgNodeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.BELG_URBN_CD
     *
     * @return the value of bhif_pay_ibank_para_info.BELG_URBN_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public String getBelgUrbnCd() {
        return belgUrbnCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.BELG_URBN_CD
     *
     * @param belgUrbnCd the value for bhif_pay_ibank_para_info.BELG_URBN_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setBelgUrbnCd(String belgUrbnCd) {
        this.belgUrbnCd = belgUrbnCd == null ? null : belgUrbnCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.PAY_IBANK_FULL_NM
     *
     * @return the value of bhif_pay_ibank_para_info.PAY_IBANK_FULL_NM
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public String getPayIbankFullNm() {
        return payIbankFullNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.PAY_IBANK_FULL_NM
     *
     * @param payIbankFullNm the value for bhif_pay_ibank_para_info.PAY_IBANK_FULL_NM
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setPayIbankFullNm(String payIbankFullNm) {
        this.payIbankFullNm = payIbankFullNm == null ? null : payIbankFullNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.PAY_IBANK_SHT_NM
     *
     * @return the value of bhif_pay_ibank_para_info.PAY_IBANK_SHT_NM
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public String getPayIbankShtNm() {
        return payIbankShtNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.PAY_IBANK_SHT_NM
     *
     * @param payIbankShtNm the value for bhif_pay_ibank_para_info.PAY_IBANK_SHT_NM
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setPayIbankShtNm(String payIbankShtNm) {
        this.payIbankShtNm = payIbankShtNm == null ? null : payIbankShtNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.JOIN_BIZ_SYS_ID_CD
     *
     * @return the value of bhif_pay_ibank_para_info.JOIN_BIZ_SYS_ID_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public String getJoinBizSysIdCd() {
        return joinBizSysIdCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.JOIN_BIZ_SYS_ID_CD
     *
     * @param joinBizSysIdCd the value for bhif_pay_ibank_para_info.JOIN_BIZ_SYS_ID_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setJoinBizSysIdCd(String joinBizSysIdCd) {
        this.joinBizSysIdCd = joinBizSysIdCd == null ? null : joinBizSysIdCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.JOIN_LARG_AMT_SYS_STAT_CD
     *
     * @return the value of bhif_pay_ibank_para_info.JOIN_LARG_AMT_SYS_STAT_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public String getJoinLargAmtSysStatCd() {
        return joinLargAmtSysStatCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.JOIN_LARG_AMT_SYS_STAT_CD
     *
     * @param joinLargAmtSysStatCd the value for bhif_pay_ibank_para_info.JOIN_LARG_AMT_SYS_STAT_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setJoinLargAmtSysStatCd(String joinLargAmtSysStatCd) {
        this.joinLargAmtSysStatCd = joinLargAmtSysStatCd == null ? null : joinLargAmtSysStatCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.JOIN_SML_AMT_SYS_STAT_CD
     *
     * @return the value of bhif_pay_ibank_para_info.JOIN_SML_AMT_SYS_STAT_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public String getJoinSmlAmtSysStatCd() {
        return joinSmlAmtSysStatCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.JOIN_SML_AMT_SYS_STAT_CD
     *
     * @param joinSmlAmtSysStatCd the value for bhif_pay_ibank_para_info.JOIN_SML_AMT_SYS_STAT_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setJoinSmlAmtSysStatCd(String joinSmlAmtSysStatCd) {
        this.joinSmlAmtSysStatCd = joinSmlAmtSysStatCd == null ? null : joinSmlAmtSysStatCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.JOIN_WBANK_SYS_STAT_CD
     *
     * @return the value of bhif_pay_ibank_para_info.JOIN_WBANK_SYS_STAT_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public String getJoinWbankSysStatCd() {
        return joinWbankSysStatCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.JOIN_WBANK_SYS_STAT_CD
     *
     * @param joinWbankSysStatCd the value for bhif_pay_ibank_para_info.JOIN_WBANK_SYS_STAT_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setJoinWbankSysStatCd(String joinWbankSysStatCd) {
        this.joinWbankSysStatCd = joinWbankSysStatCd == null ? null : joinWbankSysStatCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.ADDR
     *
     * @return the value of bhif_pay_ibank_para_info.ADDR
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.ADDR
     *
     * @param addr the value for bhif_pay_ibank_para_info.ADDR
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.ZIP_CD
     *
     * @return the value of bhif_pay_ibank_para_info.ZIP_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public String getZipCd() {
        return zipCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.ZIP_CD
     *
     * @param zipCd the value for bhif_pay_ibank_para_info.ZIP_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setZipCd(String zipCd) {
        this.zipCd = zipCd == null ? null : zipCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.CONT_TEL
     *
     * @return the value of bhif_pay_ibank_para_info.CONT_TEL
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public String getContTel() {
        return contTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.CONT_TEL
     *
     * @param contTel the value for bhif_pay_ibank_para_info.CONT_TEL
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setContTel(String contTel) {
        this.contTel = contTel == null ? null : contTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.EML_ADDR
     *
     * @return the value of bhif_pay_ibank_para_info.EML_ADDR
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public String getEmlAddr() {
        return emlAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.EML_ADDR
     *
     * @param emlAddr the value for bhif_pay_ibank_para_info.EML_ADDR
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setEmlAddr(String emlAddr) {
        this.emlAddr = emlAddr == null ? null : emlAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.SPRT_ONE_TWO_AGENT_TYP_CD
     *
     * @return the value of bhif_pay_ibank_para_info.SPRT_ONE_TWO_AGENT_TYP_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public String getSprtOneTwoAgentTypCd() {
        return sprtOneTwoAgentTypCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.SPRT_ONE_TWO_AGENT_TYP_CD
     *
     * @param sprtOneTwoAgentTypCd the value for bhif_pay_ibank_para_info.SPRT_ONE_TWO_AGENT_TYP_CD
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setSprtOneTwoAgentTypCd(String sprtOneTwoAgentTypCd) {
        this.sprtOneTwoAgentTypCd = sprtOneTwoAgentTypCd == null ? null : sprtOneTwoAgentTypCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.VALID_IND
     *
     * @return the value of bhif_pay_ibank_para_info.VALID_IND
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public String getValidInd() {
        return validInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.VALID_IND
     *
     * @param validInd the value for bhif_pay_ibank_para_info.VALID_IND
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setValidInd(String validInd) {
        this.validInd = validInd == null ? null : validInd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.SETUP_TMSTP
     *
     * @return the value of bhif_pay_ibank_para_info.SETUP_TMSTP
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public Date getSetupTmstp() {
        return setupTmstp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.SETUP_TMSTP
     *
     * @param setupTmstp the value for bhif_pay_ibank_para_info.SETUP_TMSTP
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setSetupTmstp(Date setupTmstp) {
        this.setupTmstp = setupTmstp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.UPD_TMSTP
     *
     * @return the value of bhif_pay_ibank_para_info.UPD_TMSTP
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public Date getUpdTmstp() {
        return updTmstp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.UPD_TMSTP
     *
     * @param updTmstp the value for bhif_pay_ibank_para_info.UPD_TMSTP
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setUpdTmstp(Date updTmstp) {
        this.updTmstp = updTmstp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.EFFT_DT
     *
     * @return the value of bhif_pay_ibank_para_info.EFFT_DT
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public Date getEfftDt() {
        return efftDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.EFFT_DT
     *
     * @param efftDt the value for bhif_pay_ibank_para_info.EFFT_DT
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setEfftDt(Date efftDt) {
        this.efftDt = efftDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhif_pay_ibank_para_info.INVLDTN_DT
     *
     * @return the value of bhif_pay_ibank_para_info.INVLDTN_DT
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public Date getInvldtnDt() {
        return invldtnDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhif_pay_ibank_para_info.INVLDTN_DT
     *
     * @param invldtnDt the value for bhif_pay_ibank_para_info.INVLDTN_DT
     *
     * @mbg.generated Thu Jan 18 12:23:55 CST 2018
     */
    public void setInvldtnDt(Date invldtnDt) {
        this.invldtnDt = invldtnDt;
    }
}