package com.avalon.ms.dao.entity;

public class Coursegrade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coursegrade.id
     *
     * @mbg.generated Mon Oct 09 11:15:09 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coursegrade.student_no
     *
     * @mbg.generated Mon Oct 09 11:15:09 CST 2017
     */
    private String studentNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coursegrade.course_no
     *
     * @mbg.generated Mon Oct 09 11:15:09 CST 2017
     */
    private String courseNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coursegrade.score
     *
     * @mbg.generated Mon Oct 09 11:15:09 CST 2017
     */
    private String score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coursegrade.remark
     *
     * @mbg.generated Mon Oct 09 11:15:09 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coursegrade.student_student_no
     *
     * @mbg.generated Mon Oct 09 11:15:09 CST 2017
     */
    private String studentStudentNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coursegrade.course_course_no
     *
     * @mbg.generated Mon Oct 09 11:15:09 CST 2017
     */
    private String courseCourseNo;
    
    
    private Course course;
    
    
    public Course getCourse() {
		return course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coursegrade.id
     *
     * @return the value of coursegrade.id
     *
     * @mbg.generated Mon Oct 09 11:15:09 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coursegrade.id
     *
     * @param id the value for coursegrade.id
     *
     * @mbg.generated Mon Oct 09 11:15:09 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coursegrade.student_no
     *
     * @return the value of coursegrade.student_no
     *
     * @mbg.generated Mon Oct 09 11:15:09 CST 2017
     */
    public String getStudentNo() {
        return studentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coursegrade.student_no
     *
     * @param studentNo the value for coursegrade.student_no
     *
     * @mbg.generated Mon Oct 09 11:15:09 CST 2017
     */
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo == null ? null : studentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coursegrade.course_no
     *
     * @return the value of coursegrade.course_no
     *
     * @mbg.generated Mon Oct 09 11:15:09 CST 2017
     */
    public String getCourseNo() {
        return courseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coursegrade.course_no
     *
     * @param courseNo the value for coursegrade.course_no
     *
     * @mbg.generated Mon Oct 09 11:15:09 CST 2017
     */
    public void setCourseNo(String courseNo) {
        this.courseNo = courseNo == null ? null : courseNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coursegrade.score
     *
     * @return the value of coursegrade.score
     *
     * @mbg.generated Mon Oct 09 11:15:09 CST 2017
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coursegrade.score
     *
     * @param score the value for coursegrade.score
     *
     * @mbg.generated Mon Oct 09 11:15:09 CST 2017
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coursegrade.remark
     *
     * @return the value of coursegrade.remark
     *
     * @mbg.generated Mon Oct 09 11:15:09 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coursegrade.remark
     *
     * @param remark the value for coursegrade.remark
     *
     * @mbg.generated Mon Oct 09 11:15:09 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coursegrade.student_student_no
     *
     * @return the value of coursegrade.student_student_no
     *
     * @mbg.generated Mon Oct 09 11:15:09 CST 2017
     */
    public String getStudentStudentNo() {
        return studentStudentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coursegrade.student_student_no
     *
     * @param studentStudentNo the value for coursegrade.student_student_no
     *
     * @mbg.generated Mon Oct 09 11:15:09 CST 2017
     */
    public void setStudentStudentNo(String studentStudentNo) {
        this.studentStudentNo = studentStudentNo == null ? null : studentStudentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coursegrade.course_course_no
     *
     * @return the value of coursegrade.course_course_no
     *
     * @mbg.generated Mon Oct 09 11:15:09 CST 2017
     */
    public String getCourseCourseNo() {
        return courseCourseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coursegrade.course_course_no
     *
     * @param courseCourseNo the value for coursegrade.course_course_no
     *
     * @mbg.generated Mon Oct 09 11:15:09 CST 2017
     */
    public void setCourseCourseNo(String courseCourseNo) {
        this.courseCourseNo = courseCourseNo == null ? null : courseCourseNo.trim();
    }
}