package com.avalon.ms.dao.entity;

import java.util.Date;

public class KyBranchbankinfos {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_BRANCHBANKINFOS.ID
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_BRANCHBANKINFOS.NAME
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_BRANCHBANKINFOS.CODE
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_BRANCHBANKINFOS.PROVINCE
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_BRANCHBANKINFOS.CITY
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_BRANCHBANKINFOS.TELNO
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    private String telno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_BRANCHBANKINFOS.ADDR
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_BRANCHBANKINFOS.BANKTYPE
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    private String banktype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_BRANCHBANKINFOS.BANKNAME
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    private String bankname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_BRANCHBANKINFOS.LOGICALDEL
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    private Short logicaldel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_BRANCHBANKINFOS.INSERTEDTIME
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    private Date insertedtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_BRANCHBANKINFOS.LASTMODIFIEDTIME
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    private Date lastmodifiedtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_BRANCHBANKINFOS.ID
     *
     * @return the value of KY_BRANCHBANKINFOS.ID
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_BRANCHBANKINFOS.ID
     *
     * @param id the value for KY_BRANCHBANKINFOS.ID
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_BRANCHBANKINFOS.NAME
     *
     * @return the value of KY_BRANCHBANKINFOS.NAME
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_BRANCHBANKINFOS.NAME
     *
     * @param name the value for KY_BRANCHBANKINFOS.NAME
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_BRANCHBANKINFOS.CODE
     *
     * @return the value of KY_BRANCHBANKINFOS.CODE
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_BRANCHBANKINFOS.CODE
     *
     * @param code the value for KY_BRANCHBANKINFOS.CODE
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_BRANCHBANKINFOS.PROVINCE
     *
     * @return the value of KY_BRANCHBANKINFOS.PROVINCE
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_BRANCHBANKINFOS.PROVINCE
     *
     * @param province the value for KY_BRANCHBANKINFOS.PROVINCE
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_BRANCHBANKINFOS.CITY
     *
     * @return the value of KY_BRANCHBANKINFOS.CITY
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_BRANCHBANKINFOS.CITY
     *
     * @param city the value for KY_BRANCHBANKINFOS.CITY
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_BRANCHBANKINFOS.TELNO
     *
     * @return the value of KY_BRANCHBANKINFOS.TELNO
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    public String getTelno() {
        return telno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_BRANCHBANKINFOS.TELNO
     *
     * @param telno the value for KY_BRANCHBANKINFOS.TELNO
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    public void setTelno(String telno) {
        this.telno = telno == null ? null : telno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_BRANCHBANKINFOS.ADDR
     *
     * @return the value of KY_BRANCHBANKINFOS.ADDR
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_BRANCHBANKINFOS.ADDR
     *
     * @param addr the value for KY_BRANCHBANKINFOS.ADDR
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_BRANCHBANKINFOS.BANKTYPE
     *
     * @return the value of KY_BRANCHBANKINFOS.BANKTYPE
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    public String getBanktype() {
        return banktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_BRANCHBANKINFOS.BANKTYPE
     *
     * @param banktype the value for KY_BRANCHBANKINFOS.BANKTYPE
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    public void setBanktype(String banktype) {
        this.banktype = banktype == null ? null : banktype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_BRANCHBANKINFOS.BANKNAME
     *
     * @return the value of KY_BRANCHBANKINFOS.BANKNAME
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_BRANCHBANKINFOS.BANKNAME
     *
     * @param bankname the value for KY_BRANCHBANKINFOS.BANKNAME
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    public void setBankname(String bankname) {
        this.bankname = bankname == null ? null : bankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_BRANCHBANKINFOS.LOGICALDEL
     *
     * @return the value of KY_BRANCHBANKINFOS.LOGICALDEL
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    public Short getLogicaldel() {
        return logicaldel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_BRANCHBANKINFOS.LOGICALDEL
     *
     * @param logicaldel the value for KY_BRANCHBANKINFOS.LOGICALDEL
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    public void setLogicaldel(Short logicaldel) {
        this.logicaldel = logicaldel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_BRANCHBANKINFOS.INSERTEDTIME
     *
     * @return the value of KY_BRANCHBANKINFOS.INSERTEDTIME
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    public Date getInsertedtime() {
        return insertedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_BRANCHBANKINFOS.INSERTEDTIME
     *
     * @param insertedtime the value for KY_BRANCHBANKINFOS.INSERTEDTIME
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    public void setInsertedtime(Date insertedtime) {
        this.insertedtime = insertedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_BRANCHBANKINFOS.LASTMODIFIEDTIME
     *
     * @return the value of KY_BRANCHBANKINFOS.LASTMODIFIEDTIME
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    public Date getLastmodifiedtime() {
        return lastmodifiedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_BRANCHBANKINFOS.LASTMODIFIEDTIME
     *
     * @param lastmodifiedtime the value for KY_BRANCHBANKINFOS.LASTMODIFIEDTIME
     *
     * @mbg.generated Mon Mar 19 10:32:47 CST 2018
     */
    public void setLastmodifiedtime(Date lastmodifiedtime) {
        this.lastmodifiedtime = lastmodifiedtime;
    }
}