package com.avalon.ms.dao.entity;

import java.util.Date;

public class MsOperatorRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_operator_role.id
     *
     * @mbg.generated Tue Aug 29 13:53:06 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_operator_role.operatorcode
     *
     * @mbg.generated Tue Aug 29 13:53:06 CST 2017
     */
    private String operatorcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_operator_role.roleid
     *
     * @mbg.generated Tue Aug 29 13:53:06 CST 2017
     */
    private String roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_operator_role.isactive
     *
     * @mbg.generated Tue Aug 29 13:53:06 CST 2017
     */
    private String isactive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_operator_role.createtime
     *
     * @mbg.generated Tue Aug 29 13:53:06 CST 2017
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_operator_role.creatorcode
     *
     * @mbg.generated Tue Aug 29 13:53:06 CST 2017
     */
    private String creatorcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_operator_role.modifytime
     *
     * @mbg.generated Tue Aug 29 13:53:06 CST 2017
     */
    private Date modifytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_operator_role.modifycode
     *
     * @mbg.generated Tue Aug 29 13:53:06 CST 2017
     */
    private String modifycode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_operator_role.id
     *
     * @return the value of ms_operator_role.id
     *
     * @mbg.generated Tue Aug 29 13:53:06 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_operator_role.id
     *
     * @param id the value for ms_operator_role.id
     *
     * @mbg.generated Tue Aug 29 13:53:06 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_operator_role.operatorcode
     *
     * @return the value of ms_operator_role.operatorcode
     *
     * @mbg.generated Tue Aug 29 13:53:06 CST 2017
     */
    public String getOperatorcode() {
        return operatorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_operator_role.operatorcode
     *
     * @param operatorcode the value for ms_operator_role.operatorcode
     *
     * @mbg.generated Tue Aug 29 13:53:06 CST 2017
     */
    public void setOperatorcode(String operatorcode) {
        this.operatorcode = operatorcode == null ? null : operatorcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_operator_role.roleid
     *
     * @return the value of ms_operator_role.roleid
     *
     * @mbg.generated Tue Aug 29 13:53:06 CST 2017
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_operator_role.roleid
     *
     * @param roleid the value for ms_operator_role.roleid
     *
     * @mbg.generated Tue Aug 29 13:53:06 CST 2017
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_operator_role.isactive
     *
     * @return the value of ms_operator_role.isactive
     *
     * @mbg.generated Tue Aug 29 13:53:06 CST 2017
     */
    public String getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_operator_role.isactive
     *
     * @param isactive the value for ms_operator_role.isactive
     *
     * @mbg.generated Tue Aug 29 13:53:06 CST 2017
     */
    public void setIsactive(String isactive) {
        this.isactive = isactive == null ? null : isactive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_operator_role.createtime
     *
     * @return the value of ms_operator_role.createtime
     *
     * @mbg.generated Tue Aug 29 13:53:06 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_operator_role.createtime
     *
     * @param createtime the value for ms_operator_role.createtime
     *
     * @mbg.generated Tue Aug 29 13:53:06 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_operator_role.creatorcode
     *
     * @return the value of ms_operator_role.creatorcode
     *
     * @mbg.generated Tue Aug 29 13:53:06 CST 2017
     */
    public String getCreatorcode() {
        return creatorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_operator_role.creatorcode
     *
     * @param creatorcode the value for ms_operator_role.creatorcode
     *
     * @mbg.generated Tue Aug 29 13:53:06 CST 2017
     */
    public void setCreatorcode(String creatorcode) {
        this.creatorcode = creatorcode == null ? null : creatorcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_operator_role.modifytime
     *
     * @return the value of ms_operator_role.modifytime
     *
     * @mbg.generated Tue Aug 29 13:53:06 CST 2017
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_operator_role.modifytime
     *
     * @param modifytime the value for ms_operator_role.modifytime
     *
     * @mbg.generated Tue Aug 29 13:53:06 CST 2017
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_operator_role.modifycode
     *
     * @return the value of ms_operator_role.modifycode
     *
     * @mbg.generated Tue Aug 29 13:53:06 CST 2017
     */
    public String getModifycode() {
        return modifycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_operator_role.modifycode
     *
     * @param modifycode the value for ms_operator_role.modifycode
     *
     * @mbg.generated Tue Aug 29 13:53:06 CST 2017
     */
    public void setModifycode(String modifycode) {
        this.modifycode = modifycode == null ? null : modifycode.trim();
    }
}