package com.avalon.ms.dao.entity;

public class TFile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.id
     *
     * @mbg.generated Mon Oct 30 17:51:47 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.file
     *
     * @mbg.generated Mon Oct 30 17:51:47 CST 2017
     */
    private byte[] file;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.id
     *
     * @return the value of t_file.id
     *
     * @mbg.generated Mon Oct 30 17:51:47 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.id
     *
     * @param id the value for t_file.id
     *
     * @mbg.generated Mon Oct 30 17:51:47 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.file
     *
     * @return the value of t_file.file
     *
     * @mbg.generated Mon Oct 30 17:51:47 CST 2017
     */
    public byte[] getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.file
     *
     * @param file the value for t_file.file
     *
     * @mbg.generated Mon Oct 30 17:51:47 CST 2017
     */
    public void setFile(byte[] file) {
        this.file = file;
    }
}