package com.avalon.ms.dao.entity;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbg.generated Mon Oct 09 11:14:09 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.name
     *
     * @mbg.generated Mon Oct 09 11:14:09 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.remark
     *
     * @mbg.generated Mon Oct 09 11:14:09 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_no
     *
     * @mbg.generated Mon Oct 09 11:14:09 CST 2017
     */
    private String courseNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbg.generated Mon Oct 09 11:14:09 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbg.generated Mon Oct 09 11:14:09 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.name
     *
     * @return the value of course.name
     *
     * @mbg.generated Mon Oct 09 11:14:09 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.name
     *
     * @param name the value for course.name
     *
     * @mbg.generated Mon Oct 09 11:14:09 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.remark
     *
     * @return the value of course.remark
     *
     * @mbg.generated Mon Oct 09 11:14:09 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.remark
     *
     * @param remark the value for course.remark
     *
     * @mbg.generated Mon Oct 09 11:14:09 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_no
     *
     * @return the value of course.course_no
     *
     * @mbg.generated Mon Oct 09 11:14:09 CST 2017
     */
    public String getCourseNo() {
        return courseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_no
     *
     * @param courseNo the value for course.course_no
     *
     * @mbg.generated Mon Oct 09 11:14:09 CST 2017
     */
    public void setCourseNo(String courseNo) {
        this.courseNo = courseNo == null ? null : courseNo.trim();
    }
}