package com.avalon.ms.dao.entity;

import java.math.BigDecimal;
import java.util.Date;

public class KySubaccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_SUBACCOUNT.CUSTCERTNO
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    private String custcertno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_SUBACCOUNT.MAINACCNO
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    private String mainaccno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_SUBACCOUNT.SUBACCNM
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    private String subaccnm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_SUBACCOUNT.CUSTCERTTYPE
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    private String custcerttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_SUBACCOUNT.STATUSTEXT
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    private String statustext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_SUBACCOUNT.SUBACCNO
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    private String subaccno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_SUBACCOUNT.HOSTNO
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    private String hostno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_SUBACCOUNT.BELONGS
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    private String belongs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_SUBACCOUNT.LOGICALDEL
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    private BigDecimal logicaldel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_SUBACCOUNT.INSERTTIME
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    private Date inserttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_SUBACCOUNT.UPDATETIME
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_SUBACCOUNT.CREATETIME
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_SUBACCOUNT.SEND
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    private String send;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_SUBACCOUNT.ORDERNUMBER
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    private String ordernumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_SUBACCOUNT.NOTIFIEDQYD
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    private BigDecimal notifiedqyd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_SUBACCOUNT.FILEPATH
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    private String filepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_SUBACCOUNT.PROTOCOLNO
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    private String protocolno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_SUBACCOUNT.CUSTCERTNO
     *
     * @return the value of KY_SUBACCOUNT.CUSTCERTNO
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public String getCustcertno() {
        return custcertno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_SUBACCOUNT.CUSTCERTNO
     *
     * @param custcertno the value for KY_SUBACCOUNT.CUSTCERTNO
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public void setCustcertno(String custcertno) {
        this.custcertno = custcertno == null ? null : custcertno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_SUBACCOUNT.MAINACCNO
     *
     * @return the value of KY_SUBACCOUNT.MAINACCNO
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public String getMainaccno() {
        return mainaccno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_SUBACCOUNT.MAINACCNO
     *
     * @param mainaccno the value for KY_SUBACCOUNT.MAINACCNO
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public void setMainaccno(String mainaccno) {
        this.mainaccno = mainaccno == null ? null : mainaccno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_SUBACCOUNT.SUBACCNM
     *
     * @return the value of KY_SUBACCOUNT.SUBACCNM
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public String getSubaccnm() {
        return subaccnm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_SUBACCOUNT.SUBACCNM
     *
     * @param subaccnm the value for KY_SUBACCOUNT.SUBACCNM
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public void setSubaccnm(String subaccnm) {
        this.subaccnm = subaccnm == null ? null : subaccnm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_SUBACCOUNT.CUSTCERTTYPE
     *
     * @return the value of KY_SUBACCOUNT.CUSTCERTTYPE
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public String getCustcerttype() {
        return custcerttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_SUBACCOUNT.CUSTCERTTYPE
     *
     * @param custcerttype the value for KY_SUBACCOUNT.CUSTCERTTYPE
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public void setCustcerttype(String custcerttype) {
        this.custcerttype = custcerttype == null ? null : custcerttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_SUBACCOUNT.STATUSTEXT
     *
     * @return the value of KY_SUBACCOUNT.STATUSTEXT
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public String getStatustext() {
        return statustext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_SUBACCOUNT.STATUSTEXT
     *
     * @param statustext the value for KY_SUBACCOUNT.STATUSTEXT
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public void setStatustext(String statustext) {
        this.statustext = statustext == null ? null : statustext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_SUBACCOUNT.SUBACCNO
     *
     * @return the value of KY_SUBACCOUNT.SUBACCNO
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public String getSubaccno() {
        return subaccno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_SUBACCOUNT.SUBACCNO
     *
     * @param subaccno the value for KY_SUBACCOUNT.SUBACCNO
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public void setSubaccno(String subaccno) {
        this.subaccno = subaccno == null ? null : subaccno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_SUBACCOUNT.HOSTNO
     *
     * @return the value of KY_SUBACCOUNT.HOSTNO
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public String getHostno() {
        return hostno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_SUBACCOUNT.HOSTNO
     *
     * @param hostno the value for KY_SUBACCOUNT.HOSTNO
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public void setHostno(String hostno) {
        this.hostno = hostno == null ? null : hostno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_SUBACCOUNT.BELONGS
     *
     * @return the value of KY_SUBACCOUNT.BELONGS
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public String getBelongs() {
        return belongs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_SUBACCOUNT.BELONGS
     *
     * @param belongs the value for KY_SUBACCOUNT.BELONGS
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public void setBelongs(String belongs) {
        this.belongs = belongs == null ? null : belongs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_SUBACCOUNT.LOGICALDEL
     *
     * @return the value of KY_SUBACCOUNT.LOGICALDEL
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public BigDecimal getLogicaldel() {
        return logicaldel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_SUBACCOUNT.LOGICALDEL
     *
     * @param logicaldel the value for KY_SUBACCOUNT.LOGICALDEL
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public void setLogicaldel(BigDecimal logicaldel) {
        this.logicaldel = logicaldel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_SUBACCOUNT.INSERTTIME
     *
     * @return the value of KY_SUBACCOUNT.INSERTTIME
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public Date getInserttime() {
        return inserttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_SUBACCOUNT.INSERTTIME
     *
     * @param inserttime the value for KY_SUBACCOUNT.INSERTTIME
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public void setInserttime(Date inserttime) {
        this.inserttime = inserttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_SUBACCOUNT.UPDATETIME
     *
     * @return the value of KY_SUBACCOUNT.UPDATETIME
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_SUBACCOUNT.UPDATETIME
     *
     * @param updatetime the value for KY_SUBACCOUNT.UPDATETIME
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_SUBACCOUNT.CREATETIME
     *
     * @return the value of KY_SUBACCOUNT.CREATETIME
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_SUBACCOUNT.CREATETIME
     *
     * @param createtime the value for KY_SUBACCOUNT.CREATETIME
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_SUBACCOUNT.SEND
     *
     * @return the value of KY_SUBACCOUNT.SEND
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public String getSend() {
        return send;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_SUBACCOUNT.SEND
     *
     * @param send the value for KY_SUBACCOUNT.SEND
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public void setSend(String send) {
        this.send = send == null ? null : send.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_SUBACCOUNT.ORDERNUMBER
     *
     * @return the value of KY_SUBACCOUNT.ORDERNUMBER
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public String getOrdernumber() {
        return ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_SUBACCOUNT.ORDERNUMBER
     *
     * @param ordernumber the value for KY_SUBACCOUNT.ORDERNUMBER
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public void setOrdernumber(String ordernumber) {
        this.ordernumber = ordernumber == null ? null : ordernumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_SUBACCOUNT.NOTIFIEDQYD
     *
     * @return the value of KY_SUBACCOUNT.NOTIFIEDQYD
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public BigDecimal getNotifiedqyd() {
        return notifiedqyd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_SUBACCOUNT.NOTIFIEDQYD
     *
     * @param notifiedqyd the value for KY_SUBACCOUNT.NOTIFIEDQYD
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public void setNotifiedqyd(BigDecimal notifiedqyd) {
        this.notifiedqyd = notifiedqyd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_SUBACCOUNT.FILEPATH
     *
     * @return the value of KY_SUBACCOUNT.FILEPATH
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_SUBACCOUNT.FILEPATH
     *
     * @param filepath the value for KY_SUBACCOUNT.FILEPATH
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath == null ? null : filepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_SUBACCOUNT.PROTOCOLNO
     *
     * @return the value of KY_SUBACCOUNT.PROTOCOLNO
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public String getProtocolno() {
        return protocolno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_SUBACCOUNT.PROTOCOLNO
     *
     * @param protocolno the value for KY_SUBACCOUNT.PROTOCOLNO
     *
     * @mbg.generated Mon Mar 19 10:34:02 CST 2018
     */
    public void setProtocolno(String protocolno) {
        this.protocolno = protocolno == null ? null : protocolno.trim();
    }
}