package com.avalon.ms.dao.entity;

import java.util.Date;

public class MsMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_menu.id
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_menu.menuid
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    private String menuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_menu.menuname
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    private String menuname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_menu.menuurl
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    private String menuurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_menu.fatherid
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    private String fatherid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_menu.type
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_menu.sortno
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    private String sortno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_menu.isactive
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    private String isactive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_menu.createtime
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_menu.creatorcode
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    private String creatorcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_menu.id
     *
     * @return the value of ms_menu.id
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_menu.id
     *
     * @param id the value for ms_menu.id
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_menu.menuid
     *
     * @return the value of ms_menu.menuid
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    public String getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_menu.menuid
     *
     * @param menuid the value for ms_menu.menuid
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    public void setMenuid(String menuid) {
        this.menuid = menuid == null ? null : menuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_menu.menuname
     *
     * @return the value of ms_menu.menuname
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_menu.menuname
     *
     * @param menuname the value for ms_menu.menuname
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname == null ? null : menuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_menu.menuurl
     *
     * @return the value of ms_menu.menuurl
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    public String getMenuurl() {
        return menuurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_menu.menuurl
     *
     * @param menuurl the value for ms_menu.menuurl
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    public void setMenuurl(String menuurl) {
        this.menuurl = menuurl == null ? null : menuurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_menu.fatherid
     *
     * @return the value of ms_menu.fatherid
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    public String getFatherid() {
        return fatherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_menu.fatherid
     *
     * @param fatherid the value for ms_menu.fatherid
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    public void setFatherid(String fatherid) {
        this.fatherid = fatherid == null ? null : fatherid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_menu.type
     *
     * @return the value of ms_menu.type
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_menu.type
     *
     * @param type the value for ms_menu.type
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_menu.sortno
     *
     * @return the value of ms_menu.sortno
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    public String getSortno() {
        return sortno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_menu.sortno
     *
     * @param sortno the value for ms_menu.sortno
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    public void setSortno(String sortno) {
        this.sortno = sortno == null ? null : sortno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_menu.isactive
     *
     * @return the value of ms_menu.isactive
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    public String getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_menu.isactive
     *
     * @param isactive the value for ms_menu.isactive
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    public void setIsactive(String isactive) {
        this.isactive = isactive == null ? null : isactive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_menu.createtime
     *
     * @return the value of ms_menu.createtime
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_menu.createtime
     *
     * @param createtime the value for ms_menu.createtime
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_menu.creatorcode
     *
     * @return the value of ms_menu.creatorcode
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    public String getCreatorcode() {
        return creatorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_menu.creatorcode
     *
     * @param creatorcode the value for ms_menu.creatorcode
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    public void setCreatorcode(String creatorcode) {
        this.creatorcode = creatorcode == null ? null : creatorcode.trim();
    }
}