package com.avalon.ms.dao.entity;

import java.util.Date;

public class MsRoleMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_role_menu.id
     *
     * @mbg.generated Tue Aug 29 14:00:23 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_role_menu.roleid
     *
     * @mbg.generated Tue Aug 29 14:00:23 CST 2017
     */
    private String roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_role_menu.menuid
     *
     * @mbg.generated Tue Aug 29 14:00:23 CST 2017
     */
    private String menuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_role_menu.isactive
     *
     * @mbg.generated Tue Aug 29 14:00:23 CST 2017
     */
    private String isactive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_role_menu.createtime
     *
     * @mbg.generated Tue Aug 29 14:00:23 CST 2017
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_role_menu.creatorcode
     *
     * @mbg.generated Tue Aug 29 14:00:23 CST 2017
     */
    private String creatorcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_role_menu.modifytime
     *
     * @mbg.generated Tue Aug 29 14:00:23 CST 2017
     */
    private Date modifytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_role_menu.modifycode
     *
     * @mbg.generated Tue Aug 29 14:00:23 CST 2017
     */
    private String modifycode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_role_menu.id
     *
     * @return the value of ms_role_menu.id
     *
     * @mbg.generated Tue Aug 29 14:00:23 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_role_menu.id
     *
     * @param id the value for ms_role_menu.id
     *
     * @mbg.generated Tue Aug 29 14:00:23 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_role_menu.roleid
     *
     * @return the value of ms_role_menu.roleid
     *
     * @mbg.generated Tue Aug 29 14:00:23 CST 2017
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_role_menu.roleid
     *
     * @param roleid the value for ms_role_menu.roleid
     *
     * @mbg.generated Tue Aug 29 14:00:23 CST 2017
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_role_menu.menuid
     *
     * @return the value of ms_role_menu.menuid
     *
     * @mbg.generated Tue Aug 29 14:00:23 CST 2017
     */
    public String getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_role_menu.menuid
     *
     * @param menuid the value for ms_role_menu.menuid
     *
     * @mbg.generated Tue Aug 29 14:00:23 CST 2017
     */
    public void setMenuid(String menuid) {
        this.menuid = menuid == null ? null : menuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_role_menu.isactive
     *
     * @return the value of ms_role_menu.isactive
     *
     * @mbg.generated Tue Aug 29 14:00:23 CST 2017
     */
    public String getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_role_menu.isactive
     *
     * @param isactive the value for ms_role_menu.isactive
     *
     * @mbg.generated Tue Aug 29 14:00:23 CST 2017
     */
    public void setIsactive(String isactive) {
        this.isactive = isactive == null ? null : isactive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_role_menu.createtime
     *
     * @return the value of ms_role_menu.createtime
     *
     * @mbg.generated Tue Aug 29 14:00:23 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_role_menu.createtime
     *
     * @param createtime the value for ms_role_menu.createtime
     *
     * @mbg.generated Tue Aug 29 14:00:23 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_role_menu.creatorcode
     *
     * @return the value of ms_role_menu.creatorcode
     *
     * @mbg.generated Tue Aug 29 14:00:23 CST 2017
     */
    public String getCreatorcode() {
        return creatorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_role_menu.creatorcode
     *
     * @param creatorcode the value for ms_role_menu.creatorcode
     *
     * @mbg.generated Tue Aug 29 14:00:23 CST 2017
     */
    public void setCreatorcode(String creatorcode) {
        this.creatorcode = creatorcode == null ? null : creatorcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_role_menu.modifytime
     *
     * @return the value of ms_role_menu.modifytime
     *
     * @mbg.generated Tue Aug 29 14:00:23 CST 2017
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_role_menu.modifytime
     *
     * @param modifytime the value for ms_role_menu.modifytime
     *
     * @mbg.generated Tue Aug 29 14:00:23 CST 2017
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_role_menu.modifycode
     *
     * @return the value of ms_role_menu.modifycode
     *
     * @mbg.generated Tue Aug 29 14:00:23 CST 2017
     */
    public String getModifycode() {
        return modifycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_role_menu.modifycode
     *
     * @param modifycode the value for ms_role_menu.modifycode
     *
     * @mbg.generated Tue Aug 29 14:00:23 CST 2017
     */
    public void setModifycode(String modifycode) {
        this.modifycode = modifycode == null ? null : modifycode.trim();
    }
}