package com.avalon.ms.dao.entity;

import java.util.Date;

public class MsRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_role.id
     *
     * @mbg.generated Tue Aug 29 13:59:33 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_role.roleid
     *
     * @mbg.generated Tue Aug 29 13:59:33 CST 2017
     */
    private String roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_role.rolename
     *
     * @mbg.generated Tue Aug 29 13:59:33 CST 2017
     */
    private String rolename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_role.accessmenuid
     *
     * @mbg.generated Tue Aug 29 13:59:33 CST 2017
     */
    private String accessmenuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_role.isactive
     *
     * @mbg.generated Tue Aug 29 13:59:33 CST 2017
     */
    private String isactive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_role.createtime
     *
     * @mbg.generated Tue Aug 29 13:59:33 CST 2017
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_role.creatorcode
     *
     * @mbg.generated Tue Aug 29 13:59:33 CST 2017
     */
    private String creatorcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_role.id
     *
     * @return the value of ms_role.id
     *
     * @mbg.generated Tue Aug 29 13:59:33 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_role.id
     *
     * @param id the value for ms_role.id
     *
     * @mbg.generated Tue Aug 29 13:59:33 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_role.roleid
     *
     * @return the value of ms_role.roleid
     *
     * @mbg.generated Tue Aug 29 13:59:33 CST 2017
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_role.roleid
     *
     * @param roleid the value for ms_role.roleid
     *
     * @mbg.generated Tue Aug 29 13:59:33 CST 2017
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_role.rolename
     *
     * @return the value of ms_role.rolename
     *
     * @mbg.generated Tue Aug 29 13:59:33 CST 2017
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_role.rolename
     *
     * @param rolename the value for ms_role.rolename
     *
     * @mbg.generated Tue Aug 29 13:59:33 CST 2017
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_role.accessmenuid
     *
     * @return the value of ms_role.accessmenuid
     *
     * @mbg.generated Tue Aug 29 13:59:33 CST 2017
     */
    public String getAccessmenuid() {
        return accessmenuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_role.accessmenuid
     *
     * @param accessmenuid the value for ms_role.accessmenuid
     *
     * @mbg.generated Tue Aug 29 13:59:33 CST 2017
     */
    public void setAccessmenuid(String accessmenuid) {
        this.accessmenuid = accessmenuid == null ? null : accessmenuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_role.isactive
     *
     * @return the value of ms_role.isactive
     *
     * @mbg.generated Tue Aug 29 13:59:33 CST 2017
     */
    public String getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_role.isactive
     *
     * @param isactive the value for ms_role.isactive
     *
     * @mbg.generated Tue Aug 29 13:59:33 CST 2017
     */
    public void setIsactive(String isactive) {
        this.isactive = isactive == null ? null : isactive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_role.createtime
     *
     * @return the value of ms_role.createtime
     *
     * @mbg.generated Tue Aug 29 13:59:33 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_role.createtime
     *
     * @param createtime the value for ms_role.createtime
     *
     * @mbg.generated Tue Aug 29 13:59:33 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_role.creatorcode
     *
     * @return the value of ms_role.creatorcode
     *
     * @mbg.generated Tue Aug 29 13:59:33 CST 2017
     */
    public String getCreatorcode() {
        return creatorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_role.creatorcode
     *
     * @param creatorcode the value for ms_role.creatorcode
     *
     * @mbg.generated Tue Aug 29 13:59:33 CST 2017
     */
    public void setCreatorcode(String creatorcode) {
        this.creatorcode = creatorcode == null ? null : creatorcode.trim();
    }
}