package com.avalon.ms.dao.entity;

import java.util.List;

import org.apache.ibatis.type.Alias;

import com.avalon.ms.dao.mybatis.enums.SexEnums;


@Alias("Student")
public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbg.generated Mon Oct 09 11:12:58 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_no
     *
     * @mbg.generated Mon Oct 09 11:12:58 CST 2017
     */
    private String studentNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbg.generated Mon Oct 09 11:12:58 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sex
     *
     * @mbg.generated Mon Oct 09 11:12:58 CST 2017
     */
    private SexEnums sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.remark
     *
     * @mbg.generated Mon Oct 09 11:12:58 CST 2017
     */
    private String remark;
    
    
    private List<Coursegrade> studentCourseGradeList;
    	
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbg.generated Mon Oct 09 11:12:58 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbg.generated Mon Oct 09 11:12:58 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_no
     *
     * @return the value of student.student_no
     *
     * @mbg.generated Mon Oct 09 11:12:58 CST 2017
     */
    public String getStudentNo() {
        return studentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_no
     *
     * @param studentNo the value for student.student_no
     *
     * @mbg.generated Mon Oct 09 11:12:58 CST 2017
     */
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo == null ? null : studentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbg.generated Mon Oct 09 11:12:58 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbg.generated Mon Oct 09 11:12:58 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sex
     *
     * @return the value of student.sex
     *
     * @mbg.generated Mon Oct 09 11:12:58 CST 2017
     */
    public SexEnums getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sex
     *
     * @param sex the value for student.sex
     *
     * @mbg.generated Mon Oct 09 11:12:58 CST 2017
     */
    public void setSex(SexEnums sex) {
        this.sex = sex ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.remark
     *
     * @return the value of student.remark
     *
     * @mbg.generated Mon Oct 09 11:12:58 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.remark
     *
     * @param remark the value for student.remark
     *
     * @mbg.generated Mon Oct 09 11:12:58 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

	public List<Coursegrade> getStudentCourseGradeList() {
		return studentCourseGradeList;
	}

	public void setStudentCourseGradeList(List<Coursegrade> studentCourseGradeList) {
		this.studentCourseGradeList = studentCourseGradeList;
	}
	
	public String toString(){
		return "student["+this.name+"|"+this.studentNo+"|"+this.sex+"|"+this.id+"|"+this.remark+"]";
	}
}