package com.avalon.ms.dao.mybatis.mapper;

import java.util.List;

import com.avalon.ms.dao.entity.MsMenu;

public interface MsMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_menu
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    int insert(MsMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_menu
     *
     * @mbg.generated Tue Aug 29 13:54:18 CST 2017
     */
    List<MsMenu> selectAll();
    
    
    void updateMenu(MsMenu menu);
}