package com.avalon.ms.dao.mybatis.mapper;

import com.avalon.ms.dao.entity.MsRole;
import java.util.List;

public interface MsRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_role
     *
     * @mbg.generated Tue Aug 29 13:59:33 CST 2017
     */
    int insert(MsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_role
     *
     * @mbg.generated Tue Aug 29 13:59:33 CST 2017
     */
    List<MsRole> selectAll();
}