package com.avalon.ms.dao.mybatis.mapper;

import com.avalon.ms.dao.entity.Student;
import com.avalon.ms.dao.entity.StudentProcedureBean;

import java.util.List;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Oct 09 11:12:58 CST 2017
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Oct 09 11:12:58 CST 2017
     */
    List<Student> selectAll();
    
    void count(StudentProcedureBean spb);
}